/**
 * Created by ggv on 13-11-22.
 */
var smallCoinsType = [
    {
        type:0,
        score:5,
        textureName:"小金币1.png"
    },
    {
        type:1,
        score:5,
        textureName:"小金币2.png"
    },
    {
        type:2,
        score:5,
        textureName:"小金币3.png"
    }
];
var biggerCoinType = [
    {
        type:3,
        score:15,
        textureName:"烈焰.png"
    },
    {
        type:4,
        score:15,
        textureName:"尼雅.png"
    },
    {
        type:5,
        score:15,
        textureName:"沙地.png"
    }
];
var badThings = [
    {
        type:6,
        score:-1,
        textureName:"炸弹.png"
    },
    {
        type:7,
        score:-1,
        textureName:"刀.png"
    }
];